### ISSUE TITLE
Missing type definition errors when used in JS project

### ISSUE THREAD

**Issue by tuckergordon** [hperrin/svelte-material-ui#615]
**Describe the bug**
The new reference types introduced in 2d1193c result in `svelte-check` errors when SMUI components are imported into a JavaScript Svelte project.

**To Reproduce**
1. Create a new svelte project: `npm create svelte@latest my-app`
  a. Choose "Library project"
  b. Choose "Yes, using JavaScript with JSDoc comments"
2.  Import a SMUI element into the app, e.g. ` npm i -D @smui/button`
3. Add that SMUI element to a page, e.g.
```svelte
<!-- src/routes/+page.svelte -->
<script>
  import Button, { Label } from '@smui/button';
 
  let clicked = 0;
</script>

<Button>Press</Button>
```
4. Run `npm run check` to run svelte-check. You should see errors such as:
```
path/to/node_modules/@smui/ripple/src/index.ts:1:23
Error: Cannot find type definition file for './ambient-ripple'. 
/// <reference types="./ambient-ripple" />
```

**Expected behavior**
Should be able to use SMUI components in TS and JS Svelte applications without errors.

**Additional context**
I believe the solution is to just add the `.d.ts` extension to all of these instances. E.g.

```ts
/// <reference types="./ambient-ripple.d.ts" />
```

Doing this locally fixed the errors for me.

**Comment by hperrin** [comment]
Is this still happening with the latest release?

**Comment by hperrin** [comment]
Thank you for filing this issue!

I'm going to close this issue for two reasons:

1. v9 has just been released, and I'm going to close all previous issues to be revalidated against v9.
2. SMUI is about to be migrated to the [SciActive Forge](https://forge.sciactive.com/sciactive).

**If you feel this issue should be reopened, please validate that it still applies to the newest version of SMUI (v9), then reopen it.**

As part of the migration to SciActive Forge, this repo **will remain** on GitHub as a mirror, but certain GitHub features will be disabled. This might include GitHub Issues, and I'd like to clean up all of the existing issues to make sure only issues that still apply to v9 get migrated. Thank you so much for your participation!
